### ISSUE TITLE
Не работает !lovew

### ISSUE THREAD

**Issue by Skyere** [AkihikoKen/AminoBot#1]
!love*

**Comment by AkihikoKen** [comment]
Исправил!

**Comment by Skyere** [comment]
Спасибо

**Comment by Skyere** [comment]
Кстати, как тебе идея сделать команду info для игроков

**Comment by Skyere** [comment]
То есть будет отображать их уровень, количество постов и т.д

**Comment by Skyere** [comment]
Думаю многие оценят

**Comment by AkihikoKen** [comment]
Учту.
